routes/web.php
<?php

use App\Http\Controllers\AuthorsController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserBlogController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PostController::class, 'list'])
    ->name('main');

Route::controller(PostController::class)->name('post.')
    ->group(function () {
        Route::get('/post/{post}', 'detail')
            ->name('detail')
            ->scopeBindings();
        Route::post('/post/view', 'view')
            ->name('view');
        Route::post('/post/like', 'like')
            ->name('like');
});

Route::controller(BlogController::class)->name('blog.')
    ->group(function () {
        Route::get('/blogs', 'list')
            ->name('list');
        Route::get('/blog/{blog}', 'detail')
            ->name('detail');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::controller(UserBlogController::class)->name('user.')
        ->group(function () {
            Route::get('/my-posts', 'userPosts')
                ->name('posts');
            Route::get('/my-blogs', 'userBlogs')
                ->name('blogs');
            Route::get('/blogs/subscription', 'userSubscriptions')
                ->name('subscriptions');
    });

    Route::controller(BlogController::class)->name('blog.')
        ->group(function () {
            Route::get('/blog/new', 'edit')
                ->name('new');
            Route::get('/blog/edit/{blog}', 'edit')
                ->name('edit');
            Route::post('/blog', 'save')
                ->name('create');
            Route::put('/blog/{blog}', 'save')
                ->name('save');
            Route::delete('/blog/{blog}', 'delete')
                ->name('delete');

            Route::post('/blog/subscribe/{blog}', 'subscribe')
                ->name('subscribe');
    });

    Route::controller(PostController::class)->name('post.')
        ->group(function () {
            Route::get('/post/new', 'edit')
                ->name('new');
            Route::get('/post/edit/{post}', 'edit')
                ->name('edit');
            Route::post('/post', 'save')
                ->name('create');
            Route::put('/post/{post}', 'save')
                ->name('save');
            Route::delete('/post/{post}', 'delete')
                ->name('delete');
    });

    Route::controller(CommentController::class)->name('comment.')
        ->group(function () {
            Route::post('/comment', 'save')
                ->name('create');
            Route::put('/comment/{comment}', 'save')
                ->name('save');
            Route::delete('/comment/{comment}', 'delete')
                ->name('delete');
    });

    Route::post('/authors/search', [AuthorsController::class, 'search'])
        ->name('authors.search');
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/blogs.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Blog list') }}
        </h2>
    </x-slot>

    @section('scripts')
        @vite(['resources/js/blog-list.js'])
    @endsection

    <div class="py-6">
        <x-filter-sort-form
            :sort-list="$sortList"
            :request="$request"
            :form-action="route('blog.list')"
            :form-id="'search-blogs'">
        </x-filter-sort-form>

        <div class="px-12">
            @foreach($blogs as $blog)
                <x-blog.one :blog="$blog"></x-blog.one>
            @endforeach
            {!! $blogs->links() !!}
        </div>
    </div>
</x-app-layout>

resources/views/main.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Main') }}
        </h2>
    </x-slot>

    @section('scripts')
        @vite(['resources/js/main.js'])
    @endsection

    <div class="py-6">
        <x-filter-sort-form
            :sort-list="$sortList"
            :request="$request"
            :form-action="route('main')"
            :form-id="'search-posts'">
        </x-filter-sort-form>

        <div class="px-12">
            @foreach($posts as $post)
                <x-post.one :post="$post"></x-post.one>
            @endforeach

            {!! $posts->links() !!}
        </div>
    </div>
</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>