routes/web.php
<?php

use App\Http\Controllers\AuthorsController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserBlogController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PostController::class, 'list'])
    ->name('main');

Route::controller(PostController::class)->name('post.')
    ->group(function () {
        Route::get('/post/{post}', 'detail')
            ->name('detail')
            ->scopeBindings();
        Route::post('/post/view', 'view')
            ->name('view');
        Route::post('/post/like', 'like')
            ->name('like');
});

Route::controller(BlogController::class)->name('blog.')
    ->group(function () {
        Route::get('/blogs', 'list')
            ->name('list');
        Route::get('/blog/{blog}', 'detail')
            ->name('detail');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::controller(UserBlogController::class)->name('user.')
        ->group(function () {
            Route::get('/my-posts', 'userPosts')
                ->name('posts');
            Route::get('/my-blogs', 'userBlogs')
                ->name('blogs');
            Route::get('/blogs/subscription', 'userSubscriptions')
                ->name('subscriptions');
    });

    Route::controller(BlogController::class)->name('blog.')
        ->group(function () {
            Route::get('/blog/new', 'edit')
                ->name('new');
            Route::get('/blog/edit/{blog}', 'edit')
                ->name('edit');
            Route::post('/blog', 'save')
                ->name('create');
            Route::put('/blog/{blog}', 'save')
                ->name('save');
            Route::delete('/blog/{blog}', 'delete')
                ->name('delete');

            Route::post('/blog/subscribe/{blog}', 'subscribe')
                ->name('subscribe');
    });

    Route::controller(PostController::class)->name('post.')
        ->group(function () {
            Route::get('/post/new', 'edit')
                ->name('new');
            Route::get('/post/edit/{post}', 'edit')
                ->name('edit');
            Route::post('/post', 'save')
                ->name('create');
            Route::put('/post/{post}', 'save')
                ->name('save');
            Route::delete('/post/{post}', 'delete')
                ->name('delete');
    });

    Route::controller(CommentController::class)->name('comment.')
        ->group(function () {
            Route::post('/comment', 'save')
                ->name('create');
            Route::put('/comment/{comment}', 'save')
                ->name('save');
            Route::delete('/comment/{comment}', 'delete')
                ->name('delete');
    });

    Route::post('/authors/search', [AuthorsController::class, 'search'])
        ->name('authors.search');
});

app/Http/Controllers/UserBlogController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Blog\SubscribeBlogRequest;

class UserBlogController extends Controller
{
    public function userPosts()
    {
        $userPosts = \Auth::user()
            ->posts()
            ->select(['id', 'title', 'is_published', 'created_at', 'published_at', 'owner_id'])
            ->orderBy('created_at', 'desc')
            ->paginate(\Config::get('blog.main.per-page.posts', 10))
            ->onEachSide(1);

        return view('user-blog.posts', ['userPosts' => $userPosts]);
    }

    public function userBlogs()
    {
        $userCreatedBlogs = \Auth::user()
            ->blogsOwner()
            ->select(['id', 'title', 'description', 'created_at', 'updated_at', 'owner_id'])
            ->orderBy('updated_at', 'desc')
            ->paginate(\Config::get('blog.main.per-page.blogs', 10))
            ->onEachSide(1);

        $userAuthorBlogs = \Auth::user()
            ->blogsAuthor()
            ->select(['id', 'title', 'description', 'created_at', 'updated_at', 'owner_id'])
            ->orderBy('updated_at', 'desc')
            ->paginate(\Config::get('blog.main.per-page.blogs', 15))
            ->onEachSide(1);

        return view('user-blog.blogs', [
            'userCreatedBlogs' => $userCreatedBlogs,
            'userAuthorBlogs' => $userAuthorBlogs,
        ]);
    }

    public function userSubscriptions()
    {
        $userSubscriptionBlogs = \Auth::user()
            ->subscriptions()
            ->select(['id', 'title', 'description', 'created_at' => 'blogs.created_at', 'updated_at' => 'blogs.updated_at', 'owner_id'])
            ->orderByDesc('updated_at')
            ->paginate(\Config::get('blog.main.per-page.blogs', 15))
            ->onEachSide(1);

        return view('user-blog.subscriptions', [
            'userSubscriptionBlogs' => $userSubscriptionBlogs,
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/user-blog/blogs.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('My blogs') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="px-12">
            <a href="{{ route('blog.new') }}">
                <div class="bg-green-500 py-2 px-4 w-fit rounded-lg">
                    <p class="text-white">{{ __('Create blog') }}</p>
                </div>
            </a>
            @if(!empty($userCreatedBlogs))
                <p class="pt-2 font-bold">{{ __('Blogs which you create') }}</p>
                @foreach($userCreatedBlogs as $blog)
                    <x-blog.one :blog="$blog"></x-blog.one>
                @endforeach
                {!! $userCreatedBlogs->links() !!}
            @endif

            @if(!empty($userAuthorBlogs))
                <p class="pt-2 font-bold">{{ __('Blogs where you are an author') }}</p>
                @foreach($userAuthorBlogs as $blog)
                    <x-blog.one :blog="$blog"></x-blog.one>
                @endforeach
                {!! $userAuthorBlogs->links() !!}
            @endif
        </div>
    </div>
</x-app-layout>

resources/views/user-blog/posts.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('My posts') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="px-12">
            <a href="{{ route('post.new') }}">
                <div class="bg-green-500 py-2 px-4 w-fit rounded-lg">
                    <p class="text-white">{{ __('Create post') }}</p>
                </div>
            </a>

            @foreach($userPosts as $post)
                <x-post.one :post="$post"></x-post.one>
            @endforeach

            {!! $userPosts->links() !!}
        </div>
    </div>
</x-app-layout>

resources/views/user-blog/subscriptions.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('My subscriptions') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="px-12">
            @if(!empty($userSubscriptionBlogs))
                @foreach($userSubscriptionBlogs as $blog)
                    <x-blog.one :blog="$blog"></x-blog.one>
                @endforeach
                {!! $userSubscriptionBlogs->links() !!}
            @endif
        </div>
    </div>
</x-app-layout>